title: Informatik C
description: 1a & 1r | 2025-2026
theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "sider"
    values:
      permalink: /:slug/ # Default permalink for pages in the sider directory
